# Generated by Django 4.0.5 on 2022-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_log_created_at_log_deleted_at_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
